version: '3.6'
services:
  web:
    build: ./web
    container_name: ign_web
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./web/nginx_default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/html/app
      - log-data:/var/log/nginx

  app:
    build: ./app
    container_name: ign_app
    user: www-data
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html/app
    links:
      - db

  db:
    image: mariadb:10.2
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: ign_db
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - ./db/initial.sql:/docker-entrypoint-initdb.d/initial.sql:ro
      - db-data:/var/lib/mysql
volumes:
  db-data:
  log-data:

